#!/bin/bash
set -eu

# Colors
INFO='\033[1;34m'
RED='\033[0;31m'
RESET='\e[0m' # Reset

SCRITP_NAME=$(basename $0)

export DOCKER_HOST="tcp://127.0.0.1:2375"

action=$1

# Check if an argument is suppled
if [ $# -eq 0 ]; then
    echo "No action specified"
    echo "Usage: ${SCRITP_NAME} <action>"
    echo "Actions: start, stop, status, log"
    exit 1
fi

check_root() {
    # Check if running with root
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Must be run as root${RESET}"
        exit 1
    fi
}


start() {

    check_root
    mkdir -p /var/log/docker
    cd /var/log/docker
    PATH=/usr/local/bin/docker-all:$PATH nohup \
        /usr/local/bin/docker-all/dockerd -H $DOCKER_HOST \
        > dockerd.log 2>&1 &
}

status()
{
    if [ -f /var/run/docker.pid ]; then
        echo "Docker is running with PID ${INFO}$(cat /var/run/docker.pid){RESET}"
    else
        echo "${RED}Docker is NOT running${RESET}"
        exit 1
    fi
}

stop() {
    check_root
    if [ -f /var/run/docker.pid ]; then
        kill $(cat /var/run/docker.pid)
    else
        echo "Docker is NOT running"
        exit 1
    fi
}


case $action in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    log)
        tail -f /var/log/docker/dockerd.log
        ;;
    *)
        echo "Invalid action: $action"
        exit 1
        ;;
esac


