name: Publish GitHub release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Create tar gz file
        run: tar -czvf /tmp/kindos-profile.tar.gz .

      - name: Create the GH release
        if: startsWith(github.ref, 'refs/tags/')  # Only create a release if the ref is a tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            debian12/*
            /tmp/kindos-profile.tar.gz

