name: Publish GitHub release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Create tar gz file
        run: tar -czvf kindos-profile.tar.gz install.sh debian12/

      - name: Create the GH release
        if: startsWith(github.ref, 'refs/tags/')  # Only create a release if the ref is a tag
        uses: softprops/action-gh-release@v1
        with:
          files: kindos-profile.tar.gz

